/** ISO-style codes allowed for DeepSeek online translation (~100 languages). */
export const DEEPSEEK_LANG_CODES = new Set([
  'af', 'am', 'ar', 'as', 'az', 'be', 'bg', 'bn', 'bo', 'br', 'bs', 'ca', 'ceb',
  'co', 'cs', 'cy', 'da', 'de', 'el', 'en', 'eo', 'es', 'et', 'eu', 'fa', 'fi',
  'fj', 'fr', 'fy', 'ga', 'gd', 'gl', 'gu', 'ha', 'haw', 'he', 'hi', 'hmn', 'hr',
  'hu', 'hy', 'id', 'ig', 'is', 'it', 'ja', 'jv', 'ka', 'kk', 'km', 'kn', 'ko',
  'ku', 'ky', 'la', 'lb', 'lo', 'lt', 'lv', 'mg', 'mi', 'mk', 'ml', 'mn', 'mr',
  'ms', 'mt', 'my', 'ne', 'nl', 'no', 'ny', 'oc', 'or', 'pa', 'pl', 'ps', 'pt',
  'ro', 'ru', 'rw', 'sd', 'si', 'sk', 'sl', 'sm', 'sn', 'so', 'sq', 'sr', 'st',
  'su', 'sv', 'sw', 'ta', 'te', 'tg', 'th', 'tl', 'tn', 'to', 'tr', 'ts', 'tt',
  'ug', 'uk', 'ur', 'uz', 've', 'vi', 'wo', 'xh', 'yi', 'yo', 'yue', 'zh',
  'zh-Hant', 'zu',
]);

export const DEEPSEEK_LANG_NAMES: Record<string, string> = {
  af: 'Afrikaans', am: 'Amharic', ar: 'Arabic', as: 'Assamese', az: 'Azerbaijani',
  be: 'Belarusian', bg: 'Bulgarian', bn: 'Bengali', bo: 'Tibetan', br: 'Breton',
  bs: 'Bosnian', ca: 'Catalan', ceb: 'Cebuano', co: 'Corsican', cs: 'Czech',
  cy: 'Welsh', da: 'Danish', de: 'German', el: 'Greek', en: 'English', eo: 'Esperanto',
  es: 'Spanish', et: 'Estonian', eu: 'Basque', fa: 'Persian', fi: 'Finnish',
  fj: 'Fijian', fr: 'French', fy: 'Frisian', ga: 'Irish', gd: 'Scottish Gaelic',
  gl: 'Galician', gu: 'Gujarati', ha: 'Hausa', haw: 'Hawaiian', he: 'Hebrew',
  hi: 'Hindi', hmn: 'Hmong', hr: 'Croatian', hu: 'Hungarian', hy: 'Armenian',
  id: 'Indonesian', ig: 'Igbo', is: 'Icelandic', it: 'Italian', ja: 'Japanese',
  jv: 'Javanese', ka: 'Georgian', kk: 'Kazakh', km: 'Khmer', kn: 'Kannada',
  ko: 'Korean', ku: 'Kurdish', ky: 'Kyrgyz', la: 'Latin', lb: 'Luxembourgish',
  lo: 'Lao', lt: 'Lithuanian', lv: 'Latvian', mg: 'Malagasy', mi: 'Maori',
  mk: 'Macedonian', ml: 'Malayalam', mn: 'Mongolian', mr: 'Marathi', ms: 'Malay',
  mt: 'Maltese', my: 'Burmese', ne: 'Nepali', nl: 'Dutch', no: 'Norwegian',
  ny: 'Chichewa', oc: 'Occitan', or: 'Odia', pa: 'Punjabi', pl: 'Polish',
  ps: 'Pashto', pt: 'Portuguese', ro: 'Romanian', ru: 'Russian', rw: 'Kinyarwanda',
  sd: 'Sindhi', si: 'Sinhala', sk: 'Slovak', sl: 'Slovenian', sm: 'Samoan',
  sn: 'Shona', so: 'Somali', sq: 'Albanian', sr: 'Serbian', st: 'Sesotho',
  su: 'Sundanese', sv: 'Swedish', sw: 'Swahili', ta: 'Tamil', te: 'Telugu',
  tg: 'Tajik', th: 'Thai', tl: 'Filipino', tn: 'Tswana', to: 'Tongan',
  tr: 'Turkish', ts: 'Tsonga', tt: 'Tatar', ug: 'Uyghur', uk: 'Ukrainian',
  ur: 'Urdu', uz: 'Uzbek', ve: 'Venda', vi: 'Vietnamese', wo: 'Wolof',
  xh: 'Xhosa', yi: 'Yiddish', yo: 'Yoruba', yue: 'Cantonese', zh: 'Chinese',
  'zh-Hant': 'Traditional Chinese', zu: 'Zulu',
};
