import 'language.dart';

/// ~100 languages for DeepSeek online translation.
class DeepSeekLanguages {
  DeepSeekLanguages._();

  static const List<Language> all = [
    Language(code: 'en', name: 'English', flag: '🇬🇧'),
    Language(code: 'zh', name: 'Chinese (Simplified)', flag: '🇨🇳'),
    Language(code: 'zh-Hant', name: 'Traditional Chinese', flag: '🇹🇼'),
    Language(code: 'yue', name: 'Cantonese', flag: '🇭🇰'),
    Language(code: 'es', name: 'Spanish', flag: '🇪🇸'),
    Language(code: 'fr', name: 'French', flag: '🇫🇷'),
    Language(code: 'de', name: 'German', flag: '🇩🇪'),
    Language(code: 'it', name: 'Italian', flag: '🇮🇹'),
    Language(code: 'pt', name: 'Portuguese', flag: '🇵🇹'),
    Language(code: 'ru', name: 'Russian', flag: '🇷🇺'),
    Language(code: 'ja', name: 'Japanese', flag: '🇯🇵'),
    Language(code: 'ko', name: 'Korean', flag: '🇰🇷'),
    Language(code: 'ar', name: 'Arabic', flag: '🇸🇦'),
    Language(code: 'hi', name: 'Hindi', flag: '🇮🇳'),
    Language(code: 'bn', name: 'Bengali', flag: '🇧🇩'),
    Language(code: 'ur', name: 'Urdu', flag: '🇵🇰'),
    Language(code: 'fa', name: 'Persian', flag: '🇮🇷'),
    Language(code: 'tr', name: 'Turkish', flag: '🇹🇷'),
    Language(code: 'vi', name: 'Vietnamese', flag: '🇻🇳'),
    Language(code: 'th', name: 'Thai', flag: '🇹🇭'),
    Language(code: 'id', name: 'Indonesian', flag: '🇮🇩'),
    Language(code: 'ms', name: 'Malay', flag: '🇲🇾'),
    Language(code: 'tl', name: 'Filipino', flag: '🇵🇭'),
    Language(code: 'nl', name: 'Dutch', flag: '🇳🇱'),
    Language(code: 'pl', name: 'Polish', flag: '🇵🇱'),
    Language(code: 'cs', name: 'Czech', flag: '🇨🇿'),
    Language(code: 'sk', name: 'Slovak', flag: '🇸🇰'),
    Language(code: 'uk', name: 'Ukrainian', flag: '🇺🇦'),
    Language(code: 'ro', name: 'Romanian', flag: '🇷🇴'),
    Language(code: 'hu', name: 'Hungarian', flag: '🇭🇺'),
    Language(code: 'bg', name: 'Bulgarian', flag: '🇧🇬'),
    Language(code: 'hr', name: 'Croatian', flag: '🇭🇷'),
    Language(code: 'sr', name: 'Serbian', flag: '🇷🇸'),
    Language(code: 'sl', name: 'Slovenian', flag: '🇸🇮'),
    Language(code: 'el', name: 'Greek', flag: '🇬🇷'),
    Language(code: 'he', name: 'Hebrew', flag: '🇮🇱'),
    Language(code: 'sv', name: 'Swedish', flag: '🇸🇪'),
    Language(code: 'da', name: 'Danish', flag: '🇩🇰'),
    Language(code: 'no', name: 'Norwegian', flag: '🇳🇴'),
    Language(code: 'fi', name: 'Finnish', flag: '🇫🇮'),
    Language(code: 'et', name: 'Estonian', flag: '🇪🇪'),
    Language(code: 'lv', name: 'Latvian', flag: '🇱🇻'),
    Language(code: 'lt', name: 'Lithuanian', flag: '🇱🇹'),
    Language(code: 'sq', name: 'Albanian', flag: '🇦🇱'),
    Language(code: 'mk', name: 'Macedonian', flag: '🇲🇰'),
    Language(code: 'bs', name: 'Bosnian', flag: '🇧🇦'),
    Language(code: 'ca', name: 'Catalan', flag: '🇪🇸'),
    Language(code: 'eu', name: 'Basque', flag: '🇪🇸'),
    Language(code: 'gl', name: 'Galician', flag: '🇪🇸'),
    Language(code: 'cy', name: 'Welsh', flag: '🏴'),
    Language(code: 'ga', name: 'Irish', flag: '🇮🇪'),
    Language(code: 'is', name: 'Icelandic', flag: '🇮🇸'),
    Language(code: 'mt', name: 'Maltese', flag: '🇲🇹'),
    Language(code: 'af', name: 'Afrikaans', flag: '🇿🇦'),
    Language(code: 'sw', name: 'Swahili', flag: '🇰🇪'),
    Language(code: 'zu', name: 'Zulu', flag: '🇿🇦'),
    Language(code: 'xh', name: 'Xhosa', flag: '🇿🇦'),
    Language(code: 'am', name: 'Amharic', flag: '🇪🇹'),
    Language(code: 'ha', name: 'Hausa', flag: '🇳🇬'),
    Language(code: 'yo', name: 'Yoruba', flag: '🇳🇬'),
    Language(code: 'ig', name: 'Igbo', flag: '🇳🇬'),
    Language(code: 'so', name: 'Somali', flag: '🇸🇴'),
    Language(code: 'rw', name: 'Kinyarwanda', flag: '🇷🇼'),
    Language(code: 'mg', name: 'Malagasy', flag: '🇲🇬'),
    Language(code: 'ne', name: 'Nepali', flag: '🇳🇵'),
    Language(code: 'si', name: 'Sinhala', flag: '🇱🇰'),
    Language(code: 'my', name: 'Burmese', flag: '🇲🇲'),
    Language(code: 'km', name: 'Khmer', flag: '🇰🇭'),
    Language(code: 'lo', name: 'Lao', flag: '🇱🇦'),
    Language(code: 'ka', name: 'Georgian', flag: '🇬🇪'),
    Language(code: 'hy', name: 'Armenian', flag: '🇦🇲'),
    Language(code: 'az', name: 'Azerbaijani', flag: '🇦🇿'),
    Language(code: 'kk', name: 'Kazakh', flag: '🇰🇿'),
    Language(code: 'uz', name: 'Uzbek', flag: '🇺🇿'),
    Language(code: 'ky', name: 'Kyrgyz', flag: '🇰🇬'),
    Language(code: 'tg', name: 'Tajik', flag: '🇹🇯'),
    Language(code: 'mn', name: 'Mongolian', flag: '🇲🇳'),
    Language(code: 'bo', name: 'Tibetan', flag: '🏔️'),
    Language(code: 'ug', name: 'Uyghur', flag: '🇨🇳'),
    Language(code: 'ps', name: 'Pashto', flag: '🇦🇫'),
    Language(code: 'ku', name: 'Kurdish', flag: '🇮🇶'),
    Language(code: 'sd', name: 'Sindhi', flag: '🇵🇰'),
    Language(code: 'pa', name: 'Punjabi', flag: '🇮🇳'),
    Language(code: 'gu', name: 'Gujarati', flag: '🇮🇳'),
    Language(code: 'mr', name: 'Marathi', flag: '🇮🇳'),
    Language(code: 'te', name: 'Telugu', flag: '🇮🇳'),
    Language(code: 'ta', name: 'Tamil', flag: '🇮🇳'),
    Language(code: 'kn', name: 'Kannada', flag: '🇮🇳'),
    Language(code: 'ml', name: 'Malayalam', flag: '🇮🇳'),
    Language(code: 'or', name: 'Odia', flag: '🇮🇳'),
    Language(code: 'as', name: 'Assamese', flag: '🇮🇳'),
    Language(code: 'ceb', name: 'Cebuano', flag: '🇵🇭'),
    Language(code: 'haw', name: 'Hawaiian', flag: '🇺🇸'),
    Language(code: 'jv', name: 'Javanese', flag: '🇮🇩'),
    Language(code: 'su', name: 'Sundanese', flag: '🇮🇩'),
    Language(code: 'la', name: 'Latin', flag: '🏛️'),
    Language(code: 'eo', name: 'Esperanto', flag: '🌍'),
    Language(code: 'gd', name: 'Scottish Gaelic', flag: '🏴'),
    Language(code: 'yi', name: 'Yiddish', flag: '🇮🇱'),
    Language(code: 'be', name: 'Belarusian', flag: '🇧🇾'),
    Language(code: 'tt', name: 'Tatar', flag: '🇷🇺'),
    Language(code: 'fy', name: 'Frisian', flag: '🇳🇱'),
    Language(code: 'lb', name: 'Luxembourgish', flag: '🇱🇺'),
    Language(code: 'co', name: 'Corsican', flag: '🇫🇷'),
    Language(code: 'oc', name: 'Occitan', flag: '🇫🇷'),
    Language(code: 'br', name: 'Breton', flag: '🇫🇷'),
    Language(code: 'rm', name: 'Romansh', flag: '🇨🇭'),
    Language(code: 'sm', name: 'Samoan', flag: '🇼🇸'),
    Language(code: 'to', name: 'Tongan', flag: '🇹🇴'),
    Language(code: 'fj', name: 'Fijian', flag: '🇫🇯'),
    Language(code: 'mi', name: 'Maori', flag: '🇳🇿'),
    Language(code: 'hmn', name: 'Hmong', flag: '🌏'),
    Language(code: 'ny', name: 'Chichewa', flag: '🇲🇼'),
    Language(code: 'sn', name: 'Shona', flag: '🇿🇼'),
    Language(code: 'st', name: 'Sesotho', flag: '🇱🇸'),
    Language(code: 'tn', name: 'Tswana', flag: '🇧🇼'),
    Language(code: 'ts', name: 'Tsonga', flag: '🇿🇦'),
    Language(code: 've', name: 'Venda', flag: '🇿🇦'),
    Language(code: 'wo', name: 'Wolof', flag: '🇸🇳'),
  ];

  static Language? fromCode(String code) {
    try {
      return all.firstWhere((l) => l.code == code);
    } catch (_) {
      return null;
    }
  }
}
